pay_utc_onyx_registration_page:
    pattern:  /inscription
    defaults:
        _controller: PayutcOnyxBundle:Entities/User:registration
    requirements:
        _method: get

pay_utc_onyx_registration_check_page:
    pattern:  /inscription
    defaults:
        _controller: PayutcOnyxBundle:Entities/User:registrationCheck
    requirements:
        _method: post

pay_utc_onyx_user_email_validation_page:
    pattern:  /email-validation/{encryptedId}/{encryptedToken}
    defaults:
        _controller: PayutcOnyxBundle:Entities/User:emailValidation
    requirements:
        _method: get