pay_utc_onyx_homepage:
    pattern:  /
    defaults:
        _controller: PayutcOnyxBundle:Home/Home:index
    requirements:
        _method: get

pay_utc_onyx_login_page:
    pattern:  /login
    defaults:
        _controller: PayutcOnyxBundle:Authentication:login
    requirements:
        _method: get

pay_utc_onyx_login_check_page:
    pattern:  /login_check
    requirements:
        _method: post

pay_utc_onyx_logout_page:
    pattern:  /logout
    requirements:
        _method: get