services:
  cas.security.authentication.provider:
    class:  Payutc\OnyxBundle\Security\Authentication\Provider\CasProvider
    arguments: ['', %kernel.cache_dir%/security/nonces, @doctrine.orm.entity_manager, @security.encoder_factory]

  cas.security.authentication.listener:
    class:  Payutc\OnyxBundle\Security\Firewall\CasListener
    arguments: [@security.context, @security.authentication.manager]
